// Code generated by the Encore 1.49.1 client generator. DO NOT EDIT.

// Disable eslint, jshint, and jslint for this file.
/* eslint-disable */
/* jshint ignore:start */
/*jslint-disable*/
import type { CookieWithOptions } from "encore.dev/api";

/**
 * BaseURL is the base URL for calling the Encore application's API.
 */
export type BaseURL = string

export const Local: BaseURL = "http://localhost:4000"

/**
 * Environment returns a BaseURL for calling the cloud environment with the given name.
 */
export function Environment(name: string): BaseURL {
    return `https://${name}-.encr.app`
}

/**
 * PreviewEnv returns a BaseURL for calling the preview environment with the given PR number.
 */
export function PreviewEnv(pr: number | string): BaseURL {
    return Environment(`pr${pr}`)
}

const BROWSER = typeof globalThis === "object" && ("window" in globalThis);

/**
 * Client is an API client for the  Encore application.
 */
export class Client {
    public readonly announcements: announcements.ServiceClient
    public readonly companies: companies.ServiceClient
    public readonly frontend: frontend.ServiceClient
    public readonly manifesto: manifesto.ServiceClient
    public readonly ocean_monitor: ocean_monitor.ServiceClient
    public readonly payments: payments.ServiceClient
    public readonly pollution_detector: pollution_detector.ServiceClient
    public readonly user: user.ServiceClient
    private readonly options: ClientOptions
    private readonly target: string


    /**
     * Creates a Client for calling the public and authenticated APIs of your Encore application.
     *
     * @param target  The target which the client should be configured to use. See Local and Environment for options.
     * @param options Options for the client
     */
    constructor(target: BaseURL, options?: ClientOptions) {
        this.target = target
        this.options = options ?? {}
        const base = new BaseClient(this.target, this.options)
        this.announcements = new announcements.ServiceClient(base)
        this.companies = new companies.ServiceClient(base)
        this.frontend = new frontend.ServiceClient(base)
        this.manifesto = new manifesto.ServiceClient(base)
        this.ocean_monitor = new ocean_monitor.ServiceClient(base)
        this.payments = new payments.ServiceClient(base)
        this.pollution_detector = new pollution_detector.ServiceClient(base)
        this.user = new user.ServiceClient(base)
    }

    /**
     * Creates a new Encore client with the given client options set.
     *
     * @param options Client options to set. They are merged with existing options.
     **/
    public with(options: ClientOptions): Client {
        return new Client(this.target, {
            ...this.options,
            ...options,
        })
    }
}

/**
 * Import the auth handler to be able to derive the auth type
 */
import type { auth as auth_auth } from "~backend/auth/auth";

/**
 * ClientOptions allows you to override any default behaviour within the generated Encore client.
 */
export interface ClientOptions {
    /**
     * By default the client will use the inbuilt fetch function for making the API requests.
     * however you can override it with your own implementation here if you want to run custom
     * code on each API request made or response received.
     */
    fetcher?: Fetcher

    /** Default RequestInit to be used for the client */
    requestInit?: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }

    /**
     * Allows you to set the authentication data to be used for each
     * request either by passing in a static object or by passing in
     * a function which returns a new object for each request.
     */
    auth?: RequestType<typeof auth_auth> | AuthDataGenerator
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { back as api_announcements_back_back } from "~backend/announcements/back";
import { getBySlug as api_announcements_get_by_slug_getBySlug } from "~backend/announcements/get_by_slug";
import { listPublished as api_announcements_list_published_listPublished } from "~backend/announcements/list_published";
import { remind as api_announcements_remind_remind } from "~backend/announcements/remind";
import { seed as api_announcements_seed_seed } from "~backend/announcements/seed";

export namespace announcements {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.back = this.back.bind(this)
            this.getBySlug = this.getBySlug.bind(this)
            this.listPublished = this.listPublished.bind(this)
            this.remind = this.remind.bind(this)
            this.seed = this.seed.bind(this)
        }

        /**
         * Backs an announcement with a monetary contribution.
         */
        public async back(params: RequestType<typeof api_announcements_back_back>): Promise<ResponseType<typeof api_announcements_back_back>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/announcements/back`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_announcements_back_back>
        }

        /**
         * Retrieves a published announcement by its slug with optional language support.
         */
        public async getBySlug(params: RequestType<typeof api_announcements_get_by_slug_getBySlug>): Promise<ResponseType<typeof api_announcements_get_by_slug_getBySlug>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                language: params.language,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/announcements/${encodeURIComponent(params.slug)}`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_announcements_get_by_slug_getBySlug>
        }

        /**
         * Lists all published announcements with filtering and search capabilities.
         */
        public async listPublished(params: RequestType<typeof api_announcements_list_published_listPublished>): Promise<ResponseType<typeof api_announcements_list_published_listPublished>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                category: params.category,
                language: params.language,
                limit:    params.limit === undefined ? undefined : String(params.limit),
                location: params.location,
                maxGoal:  params.maxGoal === undefined ? undefined : String(params.maxGoal),
                minGoal:  params.minGoal === undefined ? undefined : String(params.minGoal),
                offset:   params.offset === undefined ? undefined : String(params.offset),
                search:   params.search,
                sortBy:   params.sortBy === undefined ? undefined : String(params.sortBy),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/announcements`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_announcements_list_published_listPublished>
        }

        /**
         * Sets a reminder for an announcement.
         */
        public async remind(params: RequestType<typeof api_announcements_remind_remind>): Promise<ResponseType<typeof api_announcements_remind_remind>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/announcements/remind`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_announcements_remind_remind>
        }

        /**
         * Seeds the database with sample announcements and translations (restricted endpoint).
         */
        public async seed(): Promise<ResponseType<typeof api_announcements_seed_seed>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/announcements/seed`, {method: "POST", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_announcements_seed_seed>
        }
    }
}


export namespace auth {
    export interface AuthParams {
        authorization?: string
    }
}

export namespace companies {
    export interface AddCommentRequest {
        content: string
    }

    export interface AddCommentResponse {
        comment: PostComment
    }

    export interface Company {
        id: number
        name: string
        type: "ngo" | "company"
        "registration_number": string
        category: string
        email: string
        phone: string
        website?: string
        address: string
        city: string
        state?: string
        "zip_code"?: string
        country: string
        description: string
        mission: string
        impact: string
        "target_audience"?: string
        "owner_id": string
        status: "pending" | "approved" | "rejected"
        "is_non_profit": boolean
        "voting_start_date"?: string
        "voting_end_date"?: string
        "voting_ends_at"?: string
        "votes_yes": number
        "votes_no": number
        "votes_abstain": number
        "created_at": string
        "updated_at": string
        "approved_at"?: string
    }

    export interface CompanyDocument {
        id: number
        "company_id": number
        "document_type": "legal" | "financial" | "reports" | "certificates" | "other"
        "file_name": string
        "file_url": string
        "file_size": number
        "mime_type"?: string
        "uploaded_at": string
    }

    export interface CompanyDocument {
        id: number
        "company_id": number
        "document_type": "legal" | "financial" | "reports" | "certificates" | "other"
        "file_name": string
        "file_key": string
        "file_size": number
        "mime_type": string
        "uploaded_by": string
        "uploaded_at": string
        "is_public": boolean
    }

    export interface CompanyImage {
        id: number
        "company_id": number
        "image_url": string
        "image_type"?: string
        "is_primary": boolean
        "uploaded_at": string
    }

    export interface CompanyProfile {
        id: number
        "company_id": number
        presentation?: string
        "logo_url"?: string
        "cover_image_url"?: string
        "social_media"?: { [key: string]: string }
        "team_members"?: any[]
        statistics?: { [key: string]: any }
        "updated_at": string
    }

    export interface CompanyVote {
        id: number
        "company_id": number
        "user_id": string
        "vote_type": "yes" | "no" | "abstain"
        "voted_at": string
    }

    export interface CreatePostRequest {
        content: string
        "image_url"?: string
    }

    export interface CreatePostResponse {
        post: Post
    }

    export interface DeleteDocumentResponse {
        success: boolean
        message: string
    }

    export interface GetCommentsRequest {
        limit?: number
        offset?: number
    }

    export interface GetCommentsResponse {
        comments: PostComment[]
        total: number
    }

    export interface GetCompaniesRequest {
        status?: "pending" | "approved" | "rejected"
        type?: "ngo" | "company"
        category?: string
        "owner_id"?: string
        limit?: number
        offset?: number
    }

    export interface GetCompaniesResponse {
        companies: {
            id: number
            name: string
            type: "ngo" | "company"
            "registration_number": string
            category: string
            email: string
            phone: string
            website?: string
            address: string
            city: string
            state?: string
            "zip_code"?: string
            country: string
            description: string
            mission: string
            impact: string
            "target_audience"?: string
            "owner_id": string
            status: "pending" | "approved" | "rejected"
            "is_non_profit": boolean
            "voting_start_date"?: string
            "voting_end_date"?: string
            "voting_ends_at"?: string
            "votes_yes": number
            "votes_no": number
            "votes_abstain": number
            "created_at": string
            "updated_at": string
            "approved_at"?: string
            documents?: CompanyDocument[]
            images?: CompanyImage[]
            profile?: CompanyProfile
        }[]
        total: number
    }

    export interface GetCompanyResponse {
        company: Company
        documents: CompanyDocument[]
        images: CompanyImage[]
        profile?: CompanyProfile
        "can_edit": boolean
        userVote?: CompanyVote
    }

    export interface GetDocumentUrlResponse {
        url: string
        "expires_in": number
    }

    export interface GetDocumentsRequest {
        "document_type"?: string
    }

    export interface GetDocumentsResponse {
        documents: CompanyDocument[]
    }

    export interface GetPostsRequest {
        limit?: number
        offset?: number
    }

    export interface GetPostsResponse {
        posts: Post[]
        total: number
    }

    export interface LikePostResponse {
        success: boolean
        "likes_count": number
    }

    export interface Post {
        id: number
        "company_id": number
        "author_id": string
        "author_name": string
        "author_avatar"?: string | null
        content: string
        "image_url"?: string | null
        "created_at": string
        "updated_at": string
        "likes_count"?: number
        "comments_count"?: number
        "has_liked"?: boolean
    }

    export interface PostComment {
        id: number
        "post_id": number
        "user_id": string
        "user_name": string
        "user_avatar"?: string | null
        content: string
        "created_at": string
    }

    export interface RegisterCompanyRequest {
        name: string
        type: "ngo" | "company"
        "registration_number": string
        category: string
        email: string
        phone: string
        website?: string
        address: string
        city: string
        state?: string
        "zip_code"?: string
        country: string
        description: string
        mission: string
        impact: string
        "target_audience"?: string
        "is_non_profit": boolean
        documents?: {
            filename: string
            data: string
            "document_type": string
        }[]
        images?: {
            filename: string
            data: string
        }[]
    }

    export interface RegisterCompanyResponse {
        company: Company
        message: string
    }

    export interface UpdateCompanyProfileRequest {
        "user_id": string
        presentation?: string
        "logo_url"?: string
        "cover_image_url"?: string
        "social_media"?: { [key: string]: string }
        "team_members"?: any[]
        statistics?: { [key: string]: any }
    }

    export interface UpdateCompanyProfileResponse {
        profile: CompanyProfile
        message: string
    }

    export interface UpdateCompanyRequest {
        "user_id": string
        name?: string
        email?: string
        phone?: string
        website?: string
        address?: string
        city?: string
        state?: string
        "zip_code"?: string
        country?: string
        description?: string
        mission?: string
        impact?: string
        "target_audience"?: string
    }

    export interface UpdateCompanyResponse {
        company: Company
        message: string
    }

    export interface UploadDocumentRequest {
        "document_type": "legal" | "financial" | "reports" | "certificates" | "other"
        "file_name": string
        data: string
        "mime_type": string
    }

    export interface UploadDocumentResponse {
        document: CompanyDocument
        message: string
    }

    export interface UploadImageRequest {
        filename: string
        data: string
        contentType: string
    }

    export interface UploadImageResponse {
        url: string
    }

    export interface VoteOnCompanyRequest {
        "vote_type": "yes" | "no" | "abstain"
    }

    export interface VoteOnCompanyResponse {
        message: string
        votes: {
            yes: number
            no: number
            abstain: number
        }
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.addComment = this.addComment.bind(this)
            this.createPost = this.createPost.bind(this)
            this.deleteDocument = this.deleteDocument.bind(this)
            this.deletePost = this.deletePost.bind(this)
            this.getComments = this.getComments.bind(this)
            this.getCompanies = this.getCompanies.bind(this)
            this.getCompany = this.getCompany.bind(this)
            this.getDocumentUrl = this.getDocumentUrl.bind(this)
            this.getDocuments = this.getDocuments.bind(this)
            this.getPosts = this.getPosts.bind(this)
            this.getUploadUrl = this.getUploadUrl.bind(this)
            this.likePost = this.likePost.bind(this)
            this.registerCompany = this.registerCompany.bind(this)
            this.updateCompany = this.updateCompany.bind(this)
            this.updateCompanyProfile = this.updateCompanyProfile.bind(this)
            this.uploadDocument = this.uploadDocument.bind(this)
            this.uploadImage = this.uploadImage.bind(this)
            this.voteOnCompany = this.voteOnCompany.bind(this)
        }

        /**
         * API: Add a comment to a post
         */
        public async addComment(post_id: number, params: AddCommentRequest): Promise<AddCommentResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/posts/${encodeURIComponent(post_id)}/comments`, JSON.stringify(params))
            return await resp.json() as AddCommentResponse
        }

        /**
         * API: Create a new post (only company owner)
         */
        public async createPost(company_id: number, params: CreatePostRequest): Promise<CreatePostResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/companies/${encodeURIComponent(company_id)}/posts`, JSON.stringify(params))
            return await resp.json() as CreatePostResponse
        }

        /**
         * API: Delete a document (only company owner)
         */
        public async deleteDocument(document_id: number): Promise<DeleteDocumentResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("DELETE", `/documents/${encodeURIComponent(document_id)}`)
            return await resp.json() as DeleteDocumentResponse
        }

        /**
         * API: Delete a post (only post owner)
         */
        public async deletePost(post_id: number): Promise<{
    success: boolean
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("DELETE", `/posts/${encodeURIComponent(post_id)}`)
            return await resp.json() as {
    success: boolean
}
        }

        /**
         * API: Get comments for a post
         */
        public async getComments(post_id: number, params: GetCommentsRequest): Promise<GetCommentsResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                limit:  params.limit === undefined ? undefined : String(params.limit),
                offset: params.offset === undefined ? undefined : String(params.offset),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/posts/${encodeURIComponent(post_id)}/comments`, undefined, {query})
            return await resp.json() as GetCommentsResponse
        }

        /**
         * API: Get companies list
         */
        public async getCompanies(params: GetCompaniesRequest): Promise<GetCompaniesResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                category:   params.category,
                limit:      params.limit === undefined ? undefined : String(params.limit),
                offset:     params.offset === undefined ? undefined : String(params.offset),
                "owner_id": params["owner_id"],
                status:     params.status === undefined ? undefined : String(params.status),
                type:       params.type === undefined ? undefined : String(params.type),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/companies`, undefined, {query})
            return await resp.json() as GetCompaniesResponse
        }

        /**
         * API: Get single company details
         */
        public async getCompany(id: number): Promise<GetCompanyResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/companies/${encodeURIComponent(id)}`)
            return await resp.json() as GetCompanyResponse
        }

        /**
         * API: Get signed URL for document download (authenticated users only)
         */
        public async getDocumentUrl(document_id: number): Promise<GetDocumentUrlResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/documents/${encodeURIComponent(document_id)}/url`)
            return await resp.json() as GetDocumentUrlResponse
        }

        /**
         * API: Get documents for a company (authenticated users only)
         */
        public async getDocuments(company_id: number, params: GetDocumentsRequest): Promise<GetDocumentsResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                "document_type": params["document_type"],
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/companies/${encodeURIComponent(company_id)}/documents`, undefined, {query})
            return await resp.json() as GetDocumentsResponse
        }

        /**
         * API: Get posts for a company
         */
        public async getPosts(company_id: number, params: GetPostsRequest): Promise<GetPostsResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                limit:  params.limit === undefined ? undefined : String(params.limit),
                offset: params.offset === undefined ? undefined : String(params.offset),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/companies/${encodeURIComponent(company_id)}/posts`, undefined, {query})
            return await resp.json() as GetPostsResponse
        }

        /**
         * API: Get signed URL for direct upload (only company owner)
         */
        public async getUploadUrl(company_id: number, params: {
    "file_name": string
    "mime_type": string
}): Promise<{
    url: string
    "file_key": string
    "expires_in": number
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/companies/${encodeURIComponent(company_id)}/documents/upload-url`, JSON.stringify(params))
            return await resp.json() as {
    url: string
    "file_key": string
    "expires_in": number
}
        }

        /**
         * API: Like/unlike a post
         */
        public async likePost(post_id: number): Promise<LikePostResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/posts/${encodeURIComponent(post_id)}/like`)
            return await resp.json() as LikePostResponse
        }

        /**
         * API: Register a new company
         */
        public async registerCompany(params: RegisterCompanyRequest): Promise<RegisterCompanyResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/companies/register`, JSON.stringify(params))
            return await resp.json() as RegisterCompanyResponse
        }

        /**
         * API: Update company (only owner can update)
         */
        public async updateCompany(id: number, params: UpdateCompanyRequest): Promise<UpdateCompanyResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("PUT", `/companies/${encodeURIComponent(id)}`, JSON.stringify(params))
            return await resp.json() as UpdateCompanyResponse
        }

        /**
         * API: Update company profile (only owner can update)
         */
        public async updateCompanyProfile(company_id: number, params: UpdateCompanyProfileRequest): Promise<UpdateCompanyProfileResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("PUT", `/companies/${encodeURIComponent(company_id)}/profile`, JSON.stringify(params))
            return await resp.json() as UpdateCompanyProfileResponse
        }

        /**
         * API: Upload a document (only company owner)
         */
        public async uploadDocument(company_id: number, params: UploadDocumentRequest): Promise<UploadDocumentResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/companies/${encodeURIComponent(company_id)}/documents`, JSON.stringify(params))
            return await resp.json() as UploadDocumentResponse
        }

        /**
         * API: Upload image separately (for markdown editor)
         */
        public async uploadImage(params: UploadImageRequest): Promise<UploadImageResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/companies/upload-image`, JSON.stringify(params))
            return await resp.json() as UploadImageResponse
        }

        /**
         * API: Vote on a company
         */
        public async voteOnCompany(company_id: number, params: VoteOnCompanyRequest): Promise<VoteOnCompanyResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/companies/${encodeURIComponent(company_id)}/vote`, JSON.stringify(params))
            return await resp.json() as VoteOnCompanyResponse
        }
    }
}

export namespace frontend {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.assets = this.assets.bind(this)
        }

        public async assets(path: string[]): Promise<void> {
            await this.baseClient.callTypedAPI("HEAD", `/frontend/${path.map(encodeURIComponent).join("/")}`)
        }
    }
}

export namespace manifesto {
    export interface CreateProposalRequest {
        title: string
        description: string
        "new_content": string
        "author_id": string
        "author_name": string
    }

    export interface ManifestoProposal {
        id: number
        title: string
        description: string
        "new_content": string
        "previous_version_id": number
        "author_id": string
        "author_name": string
        status: "voting" | "approved" | "rejected" | "expired"
        "votes_yes": number
        "votes_no": number
        "votes_abstain": number
        "created_at": string
        "expires_at": string
        "approved_at"?: string
        "rejected_at"?: string
    }

    export interface ManifestoVersion {
        id: number
        "version_number": number
        content: string
        "author_id": string
        "author_name": string
        "created_at": string
        "is_current": boolean
        "proposal_id"?: number
    }

    export interface ManifestoVersionWithTranslations {
        id: number
        "version_number": number
        content: string
        "author_id": string
        "author_name": string
        "created_at": string
        "is_current": boolean
        language?: string
        translations?: { [key: string]: string }
    }

    export interface ProposalWithTranslations {
        id: number
        title: string
        description: string
        "new_content": string
        "author_id": string
        "author_name": string
        status: string
        "votes_yes": number
        "votes_no": number
        "votes_abstain": number
        "created_at": string
        "expires_at": string
        language: string
    }

    export interface VoteRequest {
        "proposal_id": number
        "user_id": string
        "vote_type": "yes" | "no" | "abstain"
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.createProposal = this.createProposal.bind(this)
            this.getCurrent = this.getCurrent.bind(this)
            this.getHistory = this.getHistory.bind(this)
            this.getManifestoWithTranslations = this.getManifestoWithTranslations.bind(this)
            this.getProposal = this.getProposal.bind(this)
            this.getProposalWithTranslations = this.getProposalWithTranslations.bind(this)
            this.getProposals = this.getProposals.bind(this)
            this.getUserVote = this.getUserVote.bind(this)
            this.getVersion = this.getVersion.bind(this)
            this.voteOnProposal = this.voteOnProposal.bind(this)
        }

        /**
         * Create new proposal
         */
        public async createProposal(params: CreateProposalRequest): Promise<{
    proposal: ManifestoProposal
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/manifesto/proposal`, JSON.stringify(params))
            return await resp.json() as {
    proposal: ManifestoProposal
}
        }

        /**
         * Get current manifesto
         */
        public async getCurrent(): Promise<{
    manifesto: ManifestoVersion
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/manifesto/current`)
            return await resp.json() as {
    manifesto: ManifestoVersion
}
        }

        /**
         * Get all versions history
         */
        public async getHistory(): Promise<{
    versions: ManifestoVersion[]
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/manifesto/history`)
            return await resp.json() as {
    versions: ManifestoVersion[]
}
        }

        /**
         * Get manifesto version with translations
         */
        public async getManifestoWithTranslations(id: string, params: {
    language?: string
}): Promise<{
    manifesto: ManifestoVersionWithTranslations
}> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                language: params.language,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/manifesto/${encodeURIComponent(id)}/translations`, undefined, {query})
            return await resp.json() as {
    manifesto: ManifestoVersionWithTranslations
}
        }

        /**
         * Get specific proposal
         */
        public async getProposal(id: string): Promise<{
    proposal: ManifestoProposal
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/manifesto/proposal/${encodeURIComponent(id)}`)
            return await resp.json() as {
    proposal: ManifestoProposal
}
        }

        /**
         * Get proposal with translations
         */
        public async getProposalWithTranslations(id: string, params: {
    language?: string
}): Promise<{
    proposal: ProposalWithTranslations
}> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                language: params.language,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/manifesto/proposal/${encodeURIComponent(id)}/translations`, undefined, {query})
            return await resp.json() as {
    proposal: ProposalWithTranslations
}
        }

        /**
         * Get all proposals
         */
        public async getProposals(params: {
    status?: string
}): Promise<{
    proposals: ManifestoProposal[]
}> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                status: params.status,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/manifesto/proposals`, undefined, {query})
            return await resp.json() as {
    proposals: ManifestoProposal[]
}
        }

        /**
         * Get user's vote for a proposal
         */
        public async getUserVote(proposalId: string, userId: string): Promise<{
    vote: string | null
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/manifesto/vote/${encodeURIComponent(proposalId)}/${encodeURIComponent(userId)}`)
            return await resp.json() as {
    vote: string | null
}
        }

        /**
         * Get specific version
         */
        public async getVersion(id: string): Promise<{
    version: ManifestoVersion
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/manifesto/version/${encodeURIComponent(id)}`)
            return await resp.json() as {
    version: ManifestoVersion
}
        }

        /**
         * Vote on proposal
         */
        public async voteOnProposal(params: VoteRequest): Promise<{
    success: boolean
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/manifesto/vote`, JSON.stringify(params))
            return await resp.json() as {
    success: boolean
}
        }
    }
}

export namespace ocean_monitor {
    export interface AddAreaRequest {
        name: string
        centerLat: number
        centerLon: number
        radiusKm: number
        target: "oil" | "plastic"
        priority?: number
    }

    export interface AddAreaResponse {
        areaId: string
        tilesCount: number
    }

    export interface BoundingBox {
        minLon: number
        minLat: number
        maxLon: number
        maxLat: number
    }

    export interface ListAreasResponse {
        areas: ScanArea[]
    }

    export interface ScanArea {
        id: string
        name: string
        center: {
            lat: number
            lon: number
        }
        radiusKm: number
        bbox: BoundingBox
        target: "oil" | "plastic"
        priority: number
        active: boolean
    }

    export interface ScanStatusResponse {
        areaId: string
        lastScanned?: string
        hasRecentScan: boolean
        totalImages: number
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.addScanArea = this.addScanArea.bind(this)
            this.downloadImage = this.downloadImage.bind(this)
            this.getScanStatus = this.getScanStatus.bind(this)
            this.listScanAreas = this.listScanAreas.bind(this)
            this.triggerScan = this.triggerScan.bind(this)
        }

        public async addScanArea(params: AddAreaRequest): Promise<AddAreaResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/ocean-monitor/areas`, JSON.stringify(params))
            return await resp.json() as AddAreaResponse
        }

        /**
         * Download captured image
         */
        public async downloadImage(method: "GET", objectKey: string[], body?: RequestInit["body"], options?: CallParameters): Promise<globalThis.Response> {
            return this.baseClient.callAPI(method, `/ocean-monitor/images/${objectKey.map(encodeURIComponent).join("/")}`, body, options)
        }

        public async getScanStatus(areaId: string): Promise<ScanStatusResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/ocean-monitor/areas/${encodeURIComponent(areaId)}/status`)
            return await resp.json() as ScanStatusResponse
        }

        public async listScanAreas(): Promise<ListAreasResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/ocean-monitor/areas`)
            return await resp.json() as ListAreasResponse
        }

        /**
         * Manual trigger endpoint for testing
         */
        public async triggerScan(): Promise<{
    message: string
    result: {
        scannedAreas: number
        totalImages: number
    }
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/ocean-monitor/trigger-scan`)
            return await resp.json() as {
    message: string
    result: {
        scannedAreas: number
        totalImages: number
    }
}
        }
    }
}

export namespace payments {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.createCheckout = this.createCheckout.bind(this)
            this.listDonations = this.listDonations.bind(this)
            this.webhook = this.webhook.bind(this)
        }

        /**
         * Creates a Polar checkout session for a donation.
         */
        public async createCheckout(params: RequestType<typeof api_payments_create_checkout_createCheckout>): Promise<ResponseType<typeof api_payments_create_checkout_createCheckout>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/payments/checkout`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_payments_create_checkout_createCheckout>
        }

        /**
         * Lists donations for an announcement with anonymized email addresses.
         */
        public async listDonations(params: RequestType<typeof api_payments_list_donations_listDonations>): Promise<ResponseType<typeof api_payments_list_donations_listDonations>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                limit:  params.limit === undefined ? undefined : String(params.limit),
                offset: params.offset === undefined ? undefined : String(params.offset),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/payments/donations/${encodeURIComponent(params.announcementId)}`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_payments_list_donations_listDonations>
        }

        /**
         * Raw handler to verify Polar webhook signatures.
         */
        public async webhook(options: PickMethods<"POST"> = {}): Promise<globalThis.Response> {
            options.method ||= "POST";
            return this.baseClient.callAPI(`/payments/webhook`, options)
        }
    }
}

export namespace pollution_detector {
    export interface AggregatedDetection {
        areaId: string
        areaName: string
        centerLat: number
        centerLon: number
        detectionCount: number
        maxSeverity: "low" | "medium" | "high" | "critical"
        totalAreaKm2: number
        pollutionTypes: string[]
        avgConfidence: number
        latestDetection: string
        imageIds: string[]
    }

    export interface AreaDetectionsResponse {
        detections: PollutionDetection[]
        images: {
            imageId: string
            objectKey: string
            tileX: number
            tileY: number
            detectedAt: string
        }[]
    }

    export interface GetDetectionResponse {
        found: boolean
        detection?: PollutionDetection
    }

    export interface GetDetectionsResponse {
        detections: PollutionDetection[]
        summary: {
            total: number
            oil: number
            plastic: number
            critical: number
            high: number
            medium: number
            low: number
        }
    }

    export interface ImageAnalysisRequest {
        imageId: string
        areaId: string
        objectKey: string
        tileX: number
        tileY: number
        target: "oil" | "plastic"
        bbox: {
            minLat: number
            minLon: number
            maxLat: number
            maxLon: number
        }
    }

    export interface PollutionDetection {
        id: string
        imageId: string
        areaId: string
        tileX: number
        tileY: number
        pollutionType: "oil" | "plastic"
        confidence: number
        severity: "low" | "medium" | "high" | "critical"
        estimatedAreaKm2: number
        description: string
        affectedRegions: any
        bbox: {
            minLat: number
            minLon: number
            maxLat: number
            maxLon: number
        }
        detectedAt: string
        verified: boolean
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.analyzeSingleImage = this.analyzeSingleImage.bind(this)
            this.getAggregatedDetections = this.getAggregatedDetections.bind(this)
            this.getDetectionById = this.getDetectionById.bind(this)
            this.getDetections = this.getDetections.bind(this)
            this.getDetectionsByArea = this.getDetectionsByArea.bind(this)
            this.triggerAnalysis = this.triggerAnalysis.bind(this)
        }

        /**
         * Analyze a specific image
         */
        public async analyzeSingleImage(params: ImageAnalysisRequest): Promise<{
    detected: boolean
    detectionId?: string
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/pollution-detector/analyze-image`, JSON.stringify(params))
            return await resp.json() as {
    detected: boolean
    detectionId?: string
}
        }

        public async getAggregatedDetections(): Promise<{
    detections: AggregatedDetection[]
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/pollution-detector/aggregated`)
            return await resp.json() as {
    detections: AggregatedDetection[]
}
        }

        public async getDetectionById(id: string): Promise<GetDetectionResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/pollution-detector/detections/${encodeURIComponent(id)}`)
            return await resp.json() as GetDetectionResponse
        }

        public async getDetections(params: {
    limit?: number
}): Promise<GetDetectionsResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                limit: params.limit === undefined ? undefined : String(params.limit),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/pollution-detector/detections`, undefined, {query})
            return await resp.json() as GetDetectionsResponse
        }

        public async getDetectionsByArea(areaId: string): Promise<AreaDetectionsResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/pollution-detector/areas/${encodeURIComponent(areaId)}/detections`)
            return await resp.json() as AreaDetectionsResponse
        }

        /**
         * Manual trigger for immediate analysis
         */
        public async triggerAnalysis(params: {
    limit?: number
}): Promise<{
    message: string
    analyzed: number
    detections: number
    jobId: string
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/pollution-detector/analyze`, JSON.stringify(params))
            return await resp.json() as {
    message: string
    analyzed: number
    detections: number
    jobId: string
}
        }
    }
}

export namespace user {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.getMe = this.getMe.bind(this)
        }

        /**
         * Returns the authenticated user's basic profile information.
         */
        public async getMe(): Promise<ResponseType<typeof api_user_get_me_getMe>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/user/me`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_user_get_me_getMe>
        }
    }
}


type PickMethods<Type> = Omit<CallParameters, "method"> & { method?: Type };

// Helper type to omit all fields that are cookies.
type OmitCookie<T> = {
  [K in keyof T as T[K] extends CookieWithOptions<any> ? never : K]: T[K];
};

type RequestType<Type extends (...args: any[]) => any> =
  Parameters<Type> extends [infer H, ...any[]]
    ? OmitCookie<H>
    : void;

type ResponseType<Type extends (...args: any[]) => any> = OmitCookie<Awaited<ReturnType<Type>>>;

function dateReviver(key: string, value: any): any {
  if (
    typeof value === "string" &&
    value.length >= 10 &&
    value.charCodeAt(0) >= 48 && // '0'
    value.charCodeAt(0) <= 57 // '9'
  ) {
    const parsedDate = new Date(value);
    if (!isNaN(parsedDate.getTime())) {
      return parsedDate;
    }
  }
  return value;
}


function encodeQuery(parts: Record<string, string | string[]>): string {
    const pairs: string[] = []
    for (const key in parts) {
        const val = (Array.isArray(parts[key]) ?  parts[key] : [parts[key]]) as string[]
        for (const v of val) {
            pairs.push(`${key}=${encodeURIComponent(v)}`)
        }
    }
    return pairs.join("&")
}

// makeRecord takes a record and strips any undefined values from it,
// and returns the same record with a narrower type.
// @ts-ignore - TS ignore because makeRecord is not always used
function makeRecord<K extends string | number | symbol, V>(record: Record<K, V | undefined>): Record<K, V> {
    for (const key in record) {
        if (record[key] === undefined) {
            delete record[key]
        }
    }
    return record as Record<K, V>
}

import {
  StreamInOutHandlerFn,
  StreamInHandlerFn,
  StreamOutHandlerFn,
} from "encore.dev/api";

type StreamRequest<Type> = Type extends
  | StreamInOutHandlerFn<any, infer Req, any>
  | StreamInHandlerFn<any, infer Req, any>
  | StreamOutHandlerFn<any, any>
  ? Req
  : never;

type StreamResponse<Type> = Type extends
  | StreamInOutHandlerFn<any, any, infer Resp>
  | StreamInHandlerFn<any, any, infer Resp>
  | StreamOutHandlerFn<any, infer Resp>
  ? Resp
  : never;


function encodeWebSocketHeaders(headers: Record<string, string>) {
    // url safe, no pad
    const base64encoded = btoa(JSON.stringify(headers))
      .replaceAll("=", "")
      .replaceAll("+", "-")
      .replaceAll("/", "_");
    return "encore.dev.headers." + base64encoded;
}

class WebSocketConnection {
    public ws: WebSocket;

    private hasUpdateHandlers: (() => void)[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        let protocols = ["encore-ws"];
        if (headers) {
            protocols.push(encodeWebSocketHeaders(headers))
        }

        this.ws = new WebSocket(url, protocols)

        this.on("error", () => {
            this.resolveHasUpdateHandlers();
        });

        this.on("close", () => {
            this.resolveHasUpdateHandlers();
        });
    }

    resolveHasUpdateHandlers() {
        const handlers = this.hasUpdateHandlers;
        this.hasUpdateHandlers = [];

        for (const handler of handlers) {
            handler()
        }
    }

    async hasUpdate() {
        // await until a new message have been received, or the socket is closed
        await new Promise((resolve) => {
            this.hasUpdateHandlers.push(() => resolve(null))
        });
    }

    on(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.addEventListener(type, handler);
    }

    off(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.removeEventListener(type, handler);
    }

    close() {
        this.ws.close();
    }
}

export class StreamInOut<Request, Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data, dateReviver));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamIn<Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data, dateReviver));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamOut<Request, Response> {
    public socket: WebSocketConnection;
    private responseValue: Promise<Response>;

    constructor(url: string, headers?: Record<string, string>) {
        let responseResolver: (_: any) => void;
        this.responseValue = new Promise((resolve) => responseResolver = resolve);

        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            responseResolver(JSON.parse(event.data, dateReviver))
        });
    }

    async response(): Promise<Response> {
        return this.responseValue;
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }
}
// CallParameters is the type of the parameters to a method call, but require headers to be a Record type
type CallParameters = Omit<RequestInit, "headers"> & {
    /** Headers to be sent with the request */
    headers?: Record<string, string>

    /** Query parameters to be sent with the request */
    query?: Record<string, string | string[]>
}

// AuthDataGenerator is a function that returns a new instance of the authentication data required by this API
export type AuthDataGenerator = () =>
  | RequestType<typeof auth_auth>
  | Promise<RequestType<typeof auth_auth> | undefined>
  | undefined;

// A fetcher is the prototype for the inbuilt Fetch function
export type Fetcher = typeof fetch;

const boundFetch = fetch.bind(this);

class BaseClient {
    readonly baseURL: string
    readonly fetcher: Fetcher
    readonly headers: Record<string, string>
    readonly requestInit: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }
    readonly authGenerator?: AuthDataGenerator

    constructor(baseURL: string, options: ClientOptions) {
        this.baseURL = baseURL
        this.headers = {}

        // Add User-Agent header if the script is running in the server
        // because browsers do not allow setting User-Agent headers to requests
        if (!BROWSER) {
            this.headers["User-Agent"] = "-Generated-TS-Client (Encore/1.49.1)";
        }

        this.requestInit = options.requestInit ?? {};

        // Setup what fetch function we'll be using in the base client
        if (options.fetcher !== undefined) {
            this.fetcher = options.fetcher
        } else {
            this.fetcher = boundFetch
        }

        // Setup an authentication data generator using the auth data token option
        if (options.auth !== undefined) {
            const auth = options.auth
            if (typeof auth === "function") {
                this.authGenerator = auth
            } else {
                this.authGenerator = () => auth
            }
        }
    }

    async getAuthData(): Promise<CallParameters | undefined> {
        let authData: RequestType<typeof auth_auth> | undefined;

        // If authorization data generator is present, call it and add the returned data to the request
        if (this.authGenerator) {
            const mayBePromise = this.authGenerator();
            if (mayBePromise instanceof Promise) {
                authData = await mayBePromise;
            } else {
                authData = mayBePromise;
            }
        }

        if (authData) {
            const data: CallParameters = {};

            data.headers = makeRecord<string, string>({
                authorization: authData.authorization,
            });

            return data;
        }

        return undefined;
    }

    // createStreamInOut sets up a stream to a streaming API endpoint.
    async createStreamInOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamInOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamInOut(this.baseURL + path + queryString, headers);
    }

    // createStreamIn sets up a stream to a streaming API endpoint.
    async createStreamIn<Response>(path: string, params?: CallParameters): Promise<StreamIn<Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamIn(this.baseURL + path + queryString, headers);
    }

    // createStreamOut sets up a stream to a streaming API endpoint.
    async createStreamOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamOut(this.baseURL + path + queryString, headers);
    }

    // callTypedAPI makes an API call, defaulting content type to "application/json"
    public async callTypedAPI(path: string, params?: CallParameters): Promise<Response> {
        return this.callAPI(path, {
            ...params,
            headers: { "Content-Type": "application/json", ...params?.headers }
        });
    }

    // callAPI is used by each generated API method to actually make the request
    public async callAPI(path: string, params?: CallParameters): Promise<Response> {
        let { query, headers, ...rest } = params ?? {}
        const init = {
            ...this.requestInit,
            ...rest,
        }

        // Merge our headers with any predefined headers
        init.headers = {...this.headers, ...init.headers, ...headers}

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                init.headers = {...init.headers, ...authData.headers};
            }
        }

        // Make the actual request
        const queryString = query ? '?' + encodeQuery(query) : ''
        const response = await this.fetcher(this.baseURL+path+queryString, init)

        // handle any error responses
        if (!response.ok) {
            // try and get the error message from the response body
            let body: APIErrorResponse = { code: ErrCode.Unknown, message: `request failed: status ${response.status}` }

            // if we can get the structured error we should, otherwise give a best effort
            try {
                const text = await response.text()

                try {
                    const jsonBody = JSON.parse(text)
                    if (isAPIErrorResponse(jsonBody)) {
                        body = jsonBody
                    } else {
                        body.message += ": " + JSON.stringify(jsonBody)
                    }
                } catch {
                    body.message += ": " + text
                }
            } catch (e) {
                // otherwise we just append the text to the error message
                body.message += ": " + String(e)
            }

            throw new APIError(response.status, body)
        }

        return response
    }
}

/**
 * APIErrorDetails represents the response from an Encore API in the case of an error
 */
interface APIErrorResponse {
    code: ErrCode
    message: string
    details?: any
}

function isAPIErrorResponse(err: any): err is APIErrorResponse {
    return (
        err !== undefined && err !== null &&
        isErrCode(err.code) &&
        typeof(err.message) === "string" &&
        (err.details === undefined || err.details === null || typeof(err.details) === "object")
    )
}

function isErrCode(code: any): code is ErrCode {
    return code !== undefined && Object.values(ErrCode).includes(code)
}

/**
 * APIError represents a structured error as returned from an Encore application.
 */
export class APIError extends Error {
    /**
     * The HTTP status code associated with the error.
     */
    public readonly status: number

    /**
     * The Encore error code
     */
    public readonly code: ErrCode

    /**
     * The error details
     */
    public readonly details?: any

    constructor(status: number, response: APIErrorResponse) {
        // extending errors causes issues after you construct them, unless you apply the following fixes
        super(response.message);

        // set error name as constructor name, make it not enumerable to keep native Error behavior
        // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new.target#new.target_in_constructors
        Object.defineProperty(this, 'name', {
            value:        'APIError',
            enumerable:   false,
            configurable: true,
        })

        // fix the prototype chain
        if ((Object as any).setPrototypeOf == undefined) {
            (this as any).__proto__ = APIError.prototype
        } else {
            Object.setPrototypeOf(this, APIError.prototype);
        }

        // capture a stack trace
        if ((Error as any).captureStackTrace !== undefined) {
            (Error as any).captureStackTrace(this, this.constructor);
        }

        this.status = status
        this.code = response.code
        this.details = response.details
    }
}

/**
 * Typeguard allowing use of an APIError's fields'
 */
export function isAPIError(err: any): err is APIError {
    return err instanceof APIError;
}

export enum ErrCode {
    /**
     * OK indicates the operation was successful.
     */
    OK = "ok",

    /**
     * Canceled indicates the operation was canceled (typically by the caller).
     *
     * Encore will generate this error code when cancellation is requested.
     */
    Canceled = "canceled",

    /**
     * Unknown error. An example of where this error may be returned is
     * if a Status value received from another address space belongs to
     * an error-space that is not known in this address space. Also
     * errors raised by APIs that do not return enough error information
     * may be converted to this error.
     *
     * Encore will generate this error code in the above two mentioned cases.
     */
    Unknown = "unknown",

    /**
     * InvalidArgument indicates client specified an invalid argument.
     * Note that this differs from FailedPrecondition. It indicates arguments
     * that are problematic regardless of the state of the system
     * (e.g., a malformed file name).
     *
     * This error code will not be generated by the gRPC framework.
     */
    InvalidArgument = "invalid_argument",

    /**
     * DeadlineExceeded means operation expired before completion.
     * For operations that change the state of the system, this error may be
     * returned even if the operation has completed successfully. For
     * example, a successful response from a server could have been delayed
     * long enough for the deadline to expire.
     *
     * The gRPC framework will generate this error code when the deadline is
     * exceeded.
     */
    DeadlineExceeded = "deadline_exceeded",

    /**
     * NotFound means some requested entity (e.g., file or directory) was
     * not found.
     *
     * This error code will not be generated by the gRPC framework.
     */
    NotFound = "not_found",

    /**
     * AlreadyExists means an attempt to create an entity failed because one
     * already exists.
     *
     * This error code will not be generated by the gRPC framework.
     */
    AlreadyExists = "already_exists",

    /**
     * PermissionDenied indicates the caller does not have permission to
     * execute the specified operation. It must not be used for rejections
     * caused by exhausting some resource (use ResourceExhausted
     * instead for those errors). It must not be
     * used if the caller cannot be identified (use Unauthenticated
     * instead for those errors).
     *
     * This error code will not be generated by the gRPC core framework,
     * but expect authentication middleware to use it.
     */
    PermissionDenied = "permission_denied",

    /**
     * ResourceExhausted indicates some resource has been exhausted, perhaps
     * a per-user quota, or perhaps the entire file system is out of space.
     *
     * This error code will be generated by the gRPC framework in
     * out-of-memory and server overload situations, or when a message is
     * larger than the configured maximum size.
     */
    ResourceExhausted = "resource_exhausted",

    /**
     * FailedPrecondition indicates operation was rejected because the
     * system is not in a state required for the operation's execution.
     * For example, directory to be deleted may be non-empty, an rmdir
     * operation is applied to a non-directory, etc.
     *
     * A litmus test that may help a service implementor in deciding
     * between FailedPrecondition, Aborted, and Unavailable:
     *  (a) Use Unavailable if the client can retry just the failing call.
     *  (b) Use Aborted if the client should retry at a higher-level
     *      (e.g., restarting a read-modify-write sequence).
     *  (c) Use FailedPrecondition if the client should not retry until
     *      the system state has been explicitly fixed. E.g., if an "rmdir"
     *      fails because the directory is non-empty, FailedPrecondition
     *      should be returned since the client should not retry unless
     *      they have first fixed up the directory by deleting files from it.
     *  (d) Use FailedPrecondition if the client performs conditional
     *      REST Get/Update/Delete on a resource and the resource on the
     *      server does not match the condition. E.g., conflicting
     *      read-modify-write on the same resource.
     *
     * This error code will not be generated by the gRPC framework.
     */
    FailedPrecondition = "failed_precondition",

    /**
     * Aborted indicates the operation was aborted, typically due to a
     * concurrency issue like sequencer check failures, transaction aborts,
     * etc.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     */
    Aborted = "aborted",

    /**
     * OutOfRange means operation was attempted past the valid range.
     * E.g., seeking or reading past end of file.
     *
     * Unlike InvalidArgument, this error indicates a problem that may
     * be fixed if the system state changes. For example, a 32-bit file
     * system will generate InvalidArgument if asked to read at an
     * offset that is not in the range [0,2^32-1], but it will generate
     * OutOfRange if asked to read from an offset past the current
     * file size.
     *
     * There is a fair bit of overlap between FailedPrecondition and
     * OutOfRange. We recommend using OutOfRange (the more specific
     * error) when it applies so that callers who are iterating through
     * a space can easily look for an OutOfRange error to detect when
     * they are done.
     *
     * This error code will not be generated by the gRPC framework.
     */
    OutOfRange = "out_of_range",

    /**
     * Unimplemented indicates operation is not implemented or not
     * supported/enabled in this service.
     *
     * This error code will be generated by the gRPC framework. Most
     * commonly, you will see this error code when a method implementation
     * is missing on the server. It can also be generated for unknown
     * compression algorithms or a disagreement as to whether an RPC should
     * be streaming.
     */
    Unimplemented = "unimplemented",

    /**
     * Internal errors. Means some invariants expected by underlying
     * system has been broken. If you see one of these errors,
     * something is very broken.
     *
     * This error code will be generated by the gRPC framework in several
     * internal error conditions.
     */
    Internal = "internal",

    /**
     * Unavailable indicates the service is currently unavailable.
     * This is a most likely a transient condition and may be corrected
     * by retrying with a backoff. Note that it is not always safe to retry
     * non-idempotent operations.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     *
     * This error code will be generated by the gRPC framework during
     * abrupt shutdown of a server process or network connection.
     */
    Unavailable = "unavailable",

    /**
     * DataLoss indicates unrecoverable data loss or corruption.
     *
     * This error code will not be generated by the gRPC framework.
     */
    DataLoss = "data_loss",

    /**
     * Unauthenticated indicates the request does not have valid
     * authentication credentials for the operation.
     *
     * The gRPC framework will generate this error code when the
     * authentication metadata is invalid or a Credentials callback fails,
     * but also expect authentication middleware to generate it.
     */
    Unauthenticated = "unauthenticated",
}

export default new Client(import.meta.env.VITE_CLIENT_TARGET, { requestInit: { credentials: "include" } });
